export const FETCH_GAMES_REQUEST = 'FETCH_GAMES_REQUEST';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';

export const FETCH_BASKET_ITEM_REQUEST = 'FETCH_BASKET_ITEM_REQUEST';
export const FETCH_BASKET_ITEM_SUCCESS = 'FETCH_BASKET_ITEM_SUCCESS';
export const FETCH_BASKET_ITEM_FAILURE = 'FETCH_BASKET_ITEM_FAILURE';

export const FINISH_TRANSACTION_REQUEST = 'FINISH_TRANSACTION_REQUEST';
export const FINISH_TRANSACTION_SUCCESS = 'FINISH_TRANSACTION_SUCCESS';
export const FINISH_TRANSACTION_FAILURE = 'FINISH_TRANSACTION_FAILURE';

export const CLEAR_TRANSACTION_ERROR = 'CLEAR_TRANSACTION_ERROR';

export const FETCH_ACTIVE_DRAWS_REQUEST = 'FETCH_ACTIVE_DRAWS_REQUEST';
export const FETCH_ACTIVE_DRAWS_SUCCESS = 'FETCH_ACTIVE_DRAWS_SUCCESS';
export const FETCH_ACTIVE_DRAWS_FAILURE = 'FETCH_ACTIVE_DRAWS_FAILURE';

export const SET_TICKET_PRICE = 'SET_TICKET_PRICE';

export const SET_BASKET_ITEM_STATUS = 'SET_BASKET_ITEM_STATUS';
export const SET_BASKET_ITEMS = 'SET_BASKET_ITEMS';
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';

export const SET_ADDITIONAL_NUMBER = 'SET_ADDITIONAL_NUMBER';

export const SET_LAST_TRANSACTIONS = 'SET_LAST_TRANSACTIONS';

export const FETCH_CONFIG_REQUEST = 'FETCH_CONFIG_REQUEST';
export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';
export const FETCH_CONFIG_FAILURE = 'FETCH_CONFIG_FAILURE';

export const SET_ACTIVE_LOTTO_ID = 'SET_ACTIVE_LOTTO_ID';

export const SET_LANGUAGE = 'SET_LANGUAGE';
